# Generated by Django 2.2.3 on 2019-08-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1000)),
                ('user_comment', models.CharField(max_length=1000)),
                ('passage_class', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('body', models.CharField(max_length=1000)),
                ('kind', models.CharField(max_length=1000)),
                ('viewer', models.CharField(max_length=1000)),
            ],
        ),
    ]
